name: 'nx-affected-list'
description: 'Github action for outputting a list of affected nx projects (apps and libs)'
inputs:
    base:
        description: Base of the current branch (usually main)
        required: false
    head:
        description: Latest commit of the current branch (usually HEAD)
        required: false

outputs:
    affected:
        description: array of affected projects (apps/libs) names
    hasAffected:
        description: true/false if there are affected projects (apps/libs)

author: 'dkhunt27'
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
    color: blue
    icon: "filter"